using System;
using System.Linq;
using System.Net;
using ProxyDivert.Core.Vpn;
using TqkLibrary.Proxy.Vpn.WireProxyCli;
using Xunit;

namespace ProxyDivert.Core.Tests;

// The input here is a file the user did not write and cannot be asked to fix: whatever their VPN
// provider generated. So the parser has to cope with the shapes that actually turn up — comments,
// odd casing, several peers, keys with "=" padding inside them — and say clearly what is missing
// when the file cannot make a tunnel.
public class WireGuardConfigParserTests
{
    private const string ProviderFile = """
        # Generated by some provider, do not edit
        [Interface]
        PrivateKey = aMc4nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa0Y=
        Address = 10.66.0.2/32, fd00:0000:1111::2/128
        DNS = 10.66.0.1, fd00:0000:1111::1
        MTU = 1420

        [Peer]
        PublicKey = bNc5nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa1Z=
        PresharedKey = cOd6nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa2A=
        AllowedIPs = 0.0.0.0/0, ::/0
        Endpoint = vpn.example.com:51820
        PersistentKeepalive = 25
        """;

    [Fact]
    public void Reads_a_providers_file_whole()
    {
        WireGuardConfig config = WireGuardConfigParser.Parse(ProviderFile);

        Assert.Equal("aMc4nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa0Y=", config.Interface.PrivateKey);
        Assert.Equal(new[] { "10.66.0.2/32", "fd00:0000:1111::2/128" }, config.Interface.Address);
        Assert.Equal(new[] { "10.66.0.1", "fd00:0000:1111::1" }, config.Interface.DNS);
        Assert.Equal(1420, config.Interface.MTU);

        WireGuardPeer peer = Assert.Single(config.Peers);
        Assert.Equal("vpn.example.com:51820", peer.Endpoint);
        Assert.Equal(new[] { "0.0.0.0/0", "::/0" }, peer.AllowedIPs);
        Assert.Equal(25, peer.PersistentKeepalive);
        Assert.NotNull(peer.PresharedKey);
    }

    [Fact]
    public void A_base64_key_keeps_its_padding()
    {
        // The value contains "=" characters of its own; splitting on every "=" would truncate the
        // key and the tunnel would fail to authenticate with a message about nothing in particular.
        WireGuardConfig config = WireGuardConfigParser.Parse(ProviderFile);

        Assert.EndsWith("=", config.Interface.PrivateKey);
        Assert.Equal(44, config.Interface.PrivateKey!.Length);
    }

    [Fact]
    public void Key_names_are_matched_whatever_the_casing()
    {
        WireGuardConfig config = WireGuardConfigParser.Parse("""
            [interface]
            privatekey = aMc4nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa0Y=
            ADDRESS = 10.0.0.2/32
            [PEER]
            PUBLICKEY = bNc5nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa1Z=
            endpoint = 1.2.3.4:51820
            allowedips = 0.0.0.0/0
            """);

        Assert.Single(config.Peers);
        Assert.Equal("1.2.3.4:51820", config.Peers[0].Endpoint);
    }

    [Fact]
    public void Two_peer_sections_make_two_peers()
    {
        WireGuardConfig config = WireGuardConfigParser.Parse("""
            [Interface]
            PrivateKey = aMc4nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa0Y=
            Address = 10.0.0.2/32

            [Peer]
            PublicKey = bNc5nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa1Z=
            Endpoint = 1.2.3.4:51820
            AllowedIPs = 10.0.0.0/24

            [Peer]
            PublicKey = cOd6nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa2A=
            Endpoint = 5.6.7.8:51820
            AllowedIPs = 0.0.0.0/0
            """);

        Assert.Equal(2, config.Peers.Count);
        Assert.Equal("5.6.7.8:51820", config.Peers[1].Endpoint);
    }

    [Fact]
    public void Comments_and_blank_lines_are_ignored()
    {
        WireGuardConfig config = WireGuardConfigParser.Parse("""
            ; a comment
            [Interface]   # trailing comment
            PrivateKey = aMc4nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa0Y=
            Address = 10.0.0.2/32

            [Peer]
            PublicKey = bNc5nMv0Kk4Rq0m2C0J8nZm6bF1LqO9j8VZ7Wq3Xa1Z=
            Endpoint = 1.2.3.4:51820
            AllowedIPs = 0.0.0.0/0
            """);

        Assert.Equal("10.0.0.2/32", config.Interface.Address.Single());
    }

    [Theory]
    [InlineData("[Interface]\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = k\nEndpoint = 1.2.3.4:1\nAllowedIPs = 0.0.0.0/0", "PrivateKey")]
    [InlineData("[Interface]\nPrivateKey = k\n[Peer]\nPublicKey = k\nEndpoint = 1.2.3.4:1\nAllowedIPs = 0.0.0.0/0", "Address")]
    [InlineData("[Interface]\nPrivateKey = k\nAddress = 10.0.0.2/32", "Peer")]
    [InlineData("[Interface]\nPrivateKey = k\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = k\nAllowedIPs = 0.0.0.0/0", "Endpoint")]
    [InlineData("[Interface]\nPrivateKey = k\nAddress = 10.0.0.2/32\n[Peer]\nPublicKey = k\nEndpoint = 1.2.3.4:1", "AllowedIPs")]
    public void An_unusable_file_says_which_part_is_missing(string text, string expectedInMessage)
    {
        FormatException ex = Assert.Throws<FormatException>(() => WireGuardConfigParser.Parse(text));

        Assert.Contains(expectedInMessage, ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void A_file_written_for_wireproxy_reveals_its_socks5_listener()
    {
        // This one is passed to wireproxy untouched, so the tool has to learn from the file itself
        // where the tunnel will be listening.
        IPEndPoint? endPoint = WireGuardConfigParser.ParseSocks5BindAddress(ProviderFile + """

            [Socks5]
            BindAddress = 127.0.0.1:25344
            """);

        Assert.Equal(new IPEndPoint(IPAddress.Loopback, 25344), endPoint);
    }

    [Fact]
    public void A_providers_file_has_no_socks5_section()
    {
        Assert.Null(WireGuardConfigParser.ParseSocks5BindAddress(ProviderFile));
    }

    [Fact]
    public void An_ipv6_bind_address_is_read_with_its_brackets_removed()
    {
        IPEndPoint? endPoint = WireGuardConfigParser.ParseSocks5BindAddress("[Socks5]\nBindAddress = [::1]:1080");

        Assert.Equal(new IPEndPoint(IPAddress.IPv6Loopback, 1080), endPoint);
    }
}
